spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: changeme
      secret-key: changeme
      oss:
        endpoint: changeme
        bucket: changeme
  application:
    name: gulimall-third-party

server:
  port: 30000