spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: LTAI4GAGxd5GxmTukuyhtxRd
      secret-key: Uys3qDPQfP1KfDJuxh0x2CLr0bJH69
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-ezebk
  application:
    name: gulimall-third-party

server:
  port: 30000